---
abstract: 'A collection of Gentoo::Overlay objects.'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  FindBin: '0'
  Path::Tiny: '0'
  Test::Fatal: '0'
  Test::More: '0.96'
  Test::Output: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.009, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Gentoo-Overlay-Group
no_index:
  directory:
    - corpus
    - t
provides:
  Gentoo::Overlay::Group:
    file: lib/Gentoo/Overlay/Group.pm
    version: '1.000001'
recommends:
  Moo: '1.000008'
requires:
  Gentoo::Overlay: '2.001001'
  Gentoo::Overlay::Exceptions: '0'
  Gentoo::Overlay::Types: '0'
  Moo: '0'
  MooX::HandlesVia: '0'
  MooseX::Has::Sugar: '0'
  Scalar::Util: '0'
  Types::Path::Tiny: '0'
  Types::Standard: '0'
  namespace::clean: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/kentnl/Gentoo-Overlay-Group/issues
  homepage: https://github.com/kentnl/Gentoo-Overlay-Group
  repository: https://github.com/kentnl/Gentoo-Overlay-Group.git
version: '1.000001'
